offset = 200000
itemdefs = {
"tf_weapon_bat" : 0,
"bat" : 200000,
"tf_weapon_bottle" : 1,
"bottle" : 200001,
"tf_weapon_fireaxe" : 2,
"fire axe" : 200002,
"tf_weapon_club" : 3,
"kukri" : 200003,
"tf_weapon_knife" : 4,
"knife" : 200004,
"tf_weapon_fists" : 5,
"fists" : 200005,
"tf_weapon_shovel" : 6,
"shovel" : 200006,
"tf_weapon_wrench" : 7,
"wrench" : 200007,
"tf_weapon_bonesaw" : 8,
"bonesaw" : 200008,
"tf_weapon_shotgun_primary" : 9,
"engineer's shotgun" : 200009,
"tf_weapon_shotgun_soldier" : 10,
"soldier's shotgun" : 200010,
"tf_weapon_shotgun_hwg" : 11,
"heavy's shotgun" : 200011,
"tf_weapon_shotgun_pyro" : 12,
"pyro's shotgun" : 200012,
"tf_weapon_scattergun" : 13,
"scattergun" : 200013,
"tf_weapon_sniperrifle" : 14,
"sniper rifle" : 200014,
"tf_weapon_minigun" : 15,
"minigun" : 200015,
"tf_weapon_smg" : 16,
"smg" : 200016,
"tf_weapon_syringegun_medic" : 17,
"syringe gun" : 200017,
"tf_weapon_rocketlauncher" : 18,
"rocket launcher" : 200018,
"tf_weapon_grenadelauncher" : 19,
"grenade launcher" : 200019,
"tf_weapon_pipebomblauncher" : 20,
"stickybomb launcher" : 200020,
"tf_weapon_flamethrower" : 21,
"flame thrower" : 200021,
"tf_weapon_pistol" : 22,
"engineer's pistol" : 200022,
"tf_weapon_pistol" : 23,
"scout's pistol" : 200023,
"tf_weapon_revolver" : 24,
"revolver" : 200024,
"tf_weapon_pda_engineer_build" : 25,
"construction pda" : 200025,
"tf_weapon_pda_engineer_destroy" : 26,
"destruction pda" : 200026,
"tf_weapon_pda_spy" : 27,
"disguise kit pda" : 200027,
"tf_weapon_builder" : 28,
"pda" : 200028,
"tf_weapon_medigun" : 29,
"medi gun" : 200029,
"tf_weapon_invis" : 30,
"invis watch" : 200030,
"tf_weapon_medigun" : 35,
"the kritzkrieg" : 200035,
"tf_weapon_syringegun_medic" : 36,
"the blutsauger" : 200036,
"tf_weapon_bonesaw" : 37,
"the ubersaw" : 200037,
"tf_weapon_fireaxe" : 38,
"the axtinguisher" : 200038,
"tf_weapon_flaregun" : 39,
"the flare gun" : 200039,
"tf_weapon_flamethrower" : 40,
"the backburner" : 200040,
"tf_weapon_minigun" : 41,
"natascha" : 200041,
"tf_weapon_lunchbox" : 42,
"sandvich" : 200042,
"tf_weapon_fists" : 43,
"the killing gloves of boxing" : 200043,
"tf_weapon_bat_wood" : 44,
"the sandman" : 200044,
"tf_weapon_scattergun" : 45,
"force-a-nature" : 200045,
"tf_weapon_lunchbox_drink" : 46,
"bonk! atomic punch" : 200046,
"tf_weapon_compound_bow" : 56,
"the huntsman" : 200056,
"tf_wearable_razorback" : 57,
"the razorback" : 200057,
"tf_weapon_jar" : 58,
"jarate" : 200058,
"tf_weapon_invis" : 59,
"the dead ringer" : 200059,
"tf_weapon_invis" : 60,
"the cloak and dagger" : 200060,
"tf_weapon_revolver" : 61,
"the ambassador" : 200061,
"tf_weapon_rocketlauncher_directhit" : 127,
"the direct hit" : 200127,
"tf_weapon_shovel" : 128,
"the equalizer" : 200128,
"tf_weapon_buff_item" : 129,
"the buff banner" : 200129,
"tf_weapon_pipebomblauncher" : 130,
"the scottish resistance" : 200130,
"tf_wearable_demoshield" : 131,
"the chargin' targe" : 200131,
"tf_weapon_sword" : 132,
"the eyelander" : 200132,
"tf_wearable" : 133,
"gunboats" : 200133,
"tf_weapon_laser_pointer" : 140,
"the wrangler" : 200140,
"tf_weapon_sentry_revenge" : 141,
"the frontier justice" : 200141,
"tf_weapon_robot_arm" : 142,
"the gunslinger" : 200142,
"tf_weapon_fireaxe" : 153,
"homewrecker" : 200153,
"tf_weapon_shovel" : 154,
"the pain train" : 200154,
"tf_weapon_wrench" : 155,
"the southern hospitality" : 200155,
"tf_weapon_lunchbox" : 159,
"the dalokohs bar" : 200159,
"tf_weapon_pistol" : 160,
"vintage lugermorph" : 200160,
"tf_weapon_revolver" : 161,
"big kill" : 200161,
"tf_weapon_lunchbox_drink" : 163,
"crit-a-cola" : 200163,
"tf_weapon_wrench" : 169,
"golden wrench" : 200169,
"tf_weapon_club" : 171,
"the tribalman's shiv" : 200171,
"tf_weapon_sword" : 172,
"the scotsman's skullcutter" : 200172,
"tf_weapon_bonesaw" : 173,
"the vita-saw" : 200173,
"tf_weapon_bat" : 190,
"bat" : 200190,
"tf_weapon_bottle" : 191,
"bottle" : 200191,
"tf_weapon_fireaxe" : 192,
"fire axe" : 200192,
"tf_weapon_club" : 193,
"kukri" : 200193,
"tf_weapon_knife" : 194,
"knife" : 200194,
"tf_weapon_fists" : 195,
"fists" : 200195,
"tf_weapon_shovel" : 196,
"shovel" : 200196,
"tf_weapon_wrench" : 197,
"wrench" : 200197,
"tf_weapon_bonesaw" : 198,
"bonesaw" : 200198,
"tf_weapon_shotgun" : 199,
"shotgun" : 200199,
"tf_weapon_scattergun" : 200,
"scattergun" : 200200,
"tf_weapon_sniperrifle" : 201,
"sniper rifle" : 200201,
"tf_weapon_minigun" : 202,
"minigun" : 200202,
"tf_weapon_smg" : 203,
"smg" : 200203,
"tf_weapon_syringegun_medic" : 204,
"syringe gun" : 200204,
"tf_weapon_rocketlauncher" : 205,
"rocket launcher" : 200205,
"tf_weapon_grenadelauncher" : 206,
"grenade launcher" : 200206,
"tf_weapon_pipebomblauncher" : 207,
"stickybomb launcher" : 200207,
"tf_weapon_flamethrower" : 208,
"flame thrower" : 200208,
"tf_weapon_pistol" : 209,
"pistol" : 200209,
"tf_weapon_revolver" : 210,
"revolver" : 200210,
"tf_weapon_medigun" : 211,
"medi gun" : 200211,
"tf_weapon_invis" : 212,
"invis watch" : 200212,
"tf_weapon_fireaxe" : 214,
"the powerjack" : 200214,
"tf_weapon_flamethrower" : 215,
"the degreaser" : 200215,
"tf_weapon_handgun_scout_primary" : 220,
"the shortstop" : 200220,
"tf_weapon_bat_fish" : 221,
"the holy mackerel" : 200221,
"tf_weapon_jar_milk" : 222,
"mad milk" : 200222,
"tf_weapon_revolver" : 224,
"l'etranger" : 200224,
"tf_weapon_knife" : 225,
"your eternal reward" : 200225,
"tf_weapon_buff_item" : 226,
"the battalion's backup" : 200226,
"tf_weapon_rocketlauncher" : 228,
"the black box" : 200228,
"tf_weapon_sniperrifle" : 230,
"the sydney sleeper" : 200230,
"tf_wearable" : 231,
"darwin's danger shield" : 200231,
"tf_weapon_club" : 232,
"the bushwacka" : 200232,
"tf_weapon_rocketlauncher" : 237,
"rocket jumper" : 200237,
"tf_weapon_fists" : 239,
"gloves of running urgently" : 200239,
"tf_wearable" : 241,
"duel minigame" : 200241,
"tf_weapon_shovel" : 264,
"frying pan" : 200264,
"tf_weapon_pipebomblauncher" : 265,
"sticky jumper" : 200265,
"tf_weapon_sword" : 266,
"horseless headless horsemann's headtaker" : 200266,
"tf_wearable" : 280,
"halloween noise maker - black cat" : 200280,
"tf_wearable" : 281,
"halloween noise maker - gremlin" : 200281,
"tf_wearable" : 282,
"halloween noise maker - werewolf" : 200282,
"tf_wearable" : 283,
"halloween noise maker - witch" : 200283,
"tf_wearable" : 284,
"halloween noise maker - banshee" : 200284,
"tf_wearable" : 286,
"halloween noise maker - crazy laugh" : 200286,
"tf_wearable" : 288,
"halloween noise maker - stabby" : 200288,
"tf_weapon_pistol" : 294,
"lugermorph" : 200294,
"tf_weapon_invis" : 297,
"enthusiast's timepiece" : 200297,
"tf_weapon_minigun" : 298,
"iron curtain" : 200298,
"tf_weapon_bonesaw" : 304,
"amputator" : 200304,
"tf_weapon_crossbow" : 305,
"crusader's crossbow" : 200305,
"tf_weapon_stickbomb" : 307,
"ullapool caber" : 200307,
"tf_weapon_grenadelauncher" : 308,
"the loch-n-load" : 200308,
"tf_weapon_fists" : 310,
"warrior's spirit" : 200310,
"tf_weapon_lunchbox" : 311,
"the buffalo steak sandvich" : 200311,
"tf_weapon_minigun" : 312,
"the brass beast" : 200312,
"tf_weapon_bat" : 317,
"the candy cane" : 200317,
"tf_weapon_bat" : 325,
"the boston basher" : 200325,
"tf_weapon_fireaxe" : 326,
"the back scratcher" : 200326,
"tf_weapon_sword" : 327,
"tf_weapon_sword" : 200327,
"tf_weapon_wrench" : 329,
"the jag" : 200329,
"tf_weapon_fists" : 331,
"fists of steel" : 200331,
"tf_weapon_fireaxe" : 348,
"sharpened volcano fragment" : 200348,
"tf_weapon_bat" : 349,
"sun-on-a-stick" : 200349,
"tf_weapon_flaregun" : 351,
"the detonator" : 200351,
"tf_weapon_buff_item" : 354,
"the concheror" : 200354,
"tf_weapon_bat" : 355,
"the fan o'war" : 200355,
"tf_weapon_knife" : 356,
"conniver's kunai" : 200356,
"tf_weapon_katana" : 357,
"the half-zatoichi" : 200357,
"tf_wearable" : 362,
"charity noise maker - bell" : 200362,
"tf_wearable" : 364,
"charity noise maker - gong" : 200364,
"tf_wearable" : 365,
"charity noise maker - koto" : 200365,
"tf_weapon_club" : 401,
"the shahanshah" : 200401,
"tf_weapon_sniperrifle_decap" : 402,
"the bazaar bargain" : 200402,
"tf_weapon_sword" : 404,
"the persian persuader" : 200404,
"tf_wearable" : 405,
"ali baba's wee booties" : 200405,
"tf_wearable_demoshield" : 406,
"the splendid screen" : 200406,
"tf_weapon_medigun" : 411,
"the quick-fix" : 200411,
"tf_weapon_syringegun_medic" : 412,
"the overdose" : 200412,
"tf_weapon_bonesaw" : 413,
"the solemn vow" : 200413,
"tf_weapon_rocketlauncher" : 414,
"the liberty launcher" : 200414,
"tf_weapon_shotgun" : 415,
"the reserve shooter" : 200415,
"tf_weapon_shovel" : 416,
"the market gardener" : 200416,
"tf_weapon_minigun" : 424,
"tomislav" : 200424,
"tf_weapon_shotgun_hwg" : 425,
"the family business" : 200425,
"tf_weapon_fists" : 426,
"the eviction notice" : 200426,
"tf_weapon_lunchbox" : 433,
"fishcake" : 200433,
"tf_weapon_particle_cannon" : 441,
"the cow mangler 5000" : 200441,
"tf_weapon_raygun" : 442,
"the righteous bison" : 200442,
"tf_wearable" : 444,
"the mantreads" : 200444,
"tf_weapon_shovel" : 447,
"the disciplinary action" : 200447,
"tf_weapon_soda_popper" : 448,
"the soda popper" : 200448,
"tf_weapon_handgun_scout_secondary" : 449,
"the winger" : 200449,
"tf_weapon_bat" : 450,
"the atomizer" : 200450,
"tf_weapon_bat" : 452,
"three-rune blade" : 200452,
"tf_weapon_fireaxe" : 457,
"the postal pummeler" : 200457,
"tf_weapon_revolver" : 460,
"the enforcer" : 200460,
"tf_weapon_knife" : 461,
"the big earner" : 200461,
"tf_weapon_fireaxe" : 466,
"the maul" : 200466,
"tf_weapon_sword" : 482,
"nessie's nine iron" : 200482,
"tf_powerup_bottle" : 489,
"powerup canteen" : 200489,
"tf_wearable" : 493,
"promotional noise maker - fireworks" : 200493,
"tf_weapon_rocketlauncher" : 513,
"the original" : 200513,
"tf_weapon_revolver" : 525,
"the diamondback" : 200525,
"tf_weapon_sniperrifle" : 526,
"the machina" : 200526,
"tf_weapon_shotgun_primary" : 527,
"the widowmaker" : 200527,
"tf_weapon_mechanical_arm" : 528,
"the short circuit" : 200528,
"tf_wearable" : 536,
"noise maker - birthday" : 200536,
"tf_wearable" : 542,
"noise maker - vuvuzela" : 200542,
"tf_weapon_bat_fish" : 572,
"unarmed combat" : 200572,
"tf_weapon_knife" : 574,
"the wanga prick" : 200574,
"tf_weapon_fists" : 587,
"apoco-fists" : 200587,
"tf_weapon_drg_pomson" : 588,
"the pomson 6000" : 200588,
"tf_weapon_wrench" : 589,
"the eureka effect" : 200589,
"tf_weapon_fireaxe" : 593,
"the third degree" : 200593,
"tf_weapon_flamethrower" : 594,
"the phlogistinator" : 200594,
"tf_weapon_flaregun_revenge" : 595,
"the manmelter" : 200595,
"tf_wearable" : 608,
"the bootlegger" : 200608,
"tf_weapon_bottle" : 609,
"the scottish handshake" : 200609,
"tf_weapon_knife" : 638,
"the sharp dresser" : 200638,
"tf_wearable" : 642,
"cozy camper" : 200642,
"tf_weapon_bat_giftwrap" : 648,
"the wrap assassin" : 200648,
"tf_weapon_knife" : 649,
"the spy-cicle" : 200649,
"tf_weapon_minigun" : 654,
"festive minigun" : 200654,
"tf_weapon_fists" : 656,
"the holiday punch" : 200656,
"tf_weapon_rocketlauncher" : 658,
"festive rocket launcher" : 200658,
"tf_weapon_flamethrower" : 659,
"festive flame thrower" : 200659,
"tf_weapon_bat" : 660,
"festive bat" : 200660,
"tf_weapon_pipebomblauncher" : 661,
"festive stickybomb launcher" : 200661,
"tf_weapon_wrench" : 662,
"festive wrench" : 200662,
"tf_weapon_medigun" : 663,
"festive medi gun" : 200663,
"tf_weapon_sniperrifle" : 664,
"festive sniper rifle" : 200664,
"tf_weapon_knife" : 665,
"festive knife" : 200665,
"tf_weapon_scattergun" : 669,
"festive scattergun" : 200669,
"tf_wearable" : 673,
"noise maker - winter 2011" : 200673,
"tf_weapon_knife" : 727,
"the black rose" : 200727,
"tf_weapon_rocketlauncher" : 730,
"the beggar's bazooka" : 200730,
"tf_weapon_builder" : 735,
"sapper" : 200735,
"tf_weapon_builder" : 736,
"sapper" : 200736,
"tf_weapon_pda_engineer_build" : 737,
"construction pda" : 200737,
"tf_weapon_fireaxe" : 739,
"the lollichop" : 200739,
"tf_weapon_flaregun" : 740,
"the scorch shot" : 200740,
"tf_weapon_flamethrower" : 741,
"the rainblower" : 200741,
"tf_weapon_charged_smg" : 751,
"the cleaner's carbine" : 200751,
"tf_weapon_sniperrifle" : 752,
"the hitman's heatmaker" : 200752,
"tf_weapon_pep_brawler_blaster" : 772,
"baby face's blaster" : 200772,
"tf_weapon_handgun_scout_secondary" : 773,
"pretty boy's pocket pistol" : 200773,
"tf_weapon_shovel" : 775,
"the escape plan" : 200775,
"tf_weapon_sniperrifle" : 792,
"silver botkiller sniper rifle mk.i" : 200792,
"tf_weapon_minigun" : 793,
"silver botkiller minigun mk.i" : 200793,
"tf_weapon_knife" : 794,
"silver botkiller knife mk.i" : 200794,
"tf_weapon_wrench" : 795,
"silver botkiller wrench mk.i" : 200795,
"tf_weapon_medigun" : 796,
"silver botkiller medi gun mk.i" : 200796,
"tf_weapon_pipebomblauncher" : 797,
"silver botkiller stickybomb launcher mk.i" : 200797,
"tf_weapon_flamethrower" : 798,
"silver botkiller flame thrower mk.i" : 200798,
"tf_weapon_scattergun" : 799,
"silver botkiller scattergun mk.i" : 200799,
"tf_weapon_rocketlauncher" : 800,
"silver botkiller rocket launcher mk.i" : 200800,
"tf_weapon_sniperrifle" : 801,
"gold botkiller sniper rifle mk.i" : 200801,
"tf_weapon_minigun" : 802,
"gold botkiller minigun mk.i" : 200802,
"tf_weapon_knife" : 803,
"gold botkiller knife mk.i" : 200803,
"tf_weapon_wrench" : 804,
"gold botkiller wrench mk.i" : 200804,
"tf_weapon_medigun" : 805,
"gold botkiller medi gun mk.i" : 200805,
"tf_weapon_pipebomblauncher" : 806,
"gold botkiller stickybomb launcher mk.i" : 200806,
"tf_weapon_flamethrower" : 807,
"gold botkiller flame thrower mk.i" : 200807,
"tf_weapon_scattergun" : 808,
"gold botkiller scattergun mk.i" : 200808,
"tf_weapon_rocketlauncher" : 809,
"gold botkiller rocket launcher mk.i" : 200809,
"tf_weapon_sapper" : 810,
"the red-tape recorder" : 200810,
"tf_weapon_minigun" : 811,
"the huo-long heater" : 200811,
"tf_weapon_cleaver" : 812,
"the flying guillotine" : 200812,
"tf_weapon_breakable_sign" : 813,
"neon annihilator" : 200813,
"tf_weapon_sapper" : 831,
"the red-tape recorder" : 200831,
"tf_weapon_minigun" : 832,
"the huo-long heater" : 200832,
"tf_weapon_cleaver" : 833,
"the flying guillotine" : 200833,
"tf_weapon_breakable_sign" : 834,
"neon annihilator" : 200834,
"tf_weapon_minigun" : 850,
"deflector" : 200850,
"tf_weapon_sniperrifle" : 851,
"the awper hand" : 200851,
"tf_weapon_lunchbox" : 863,
"robo-sandvich" : 200863,
"tf_weapon_sniperrifle" : 881,
"rust botkiller sniper rifle mk.i" : 200881,
"tf_weapon_minigun" : 882,
"rust botkiller minigun mk.i" : 200882,
"tf_weapon_knife" : 883,
"rust botkiller knife mk.i" : 200883,
"tf_weapon_wrench" : 884,
"rust botkiller wrench mk.i" : 200884,
"tf_weapon_medigun" : 885,
"rust botkiller medi gun mk.i" : 200885,
"tf_weapon_pipebomblauncher" : 886,
"rust botkiller stickybomb launcher mk.i" : 200886,
"tf_weapon_flamethrower" : 887,
"rust botkiller flame thrower mk.i" : 200887,
"tf_weapon_scattergun" : 888,
"rust botkiller scattergun mk.i" : 200888,
"tf_weapon_rocketlauncher" : 889,
"rust botkiller rocket launcher mk.i" : 200889,
"tf_weapon_sniperrifle" : 890,
"blood botkiller sniper rifle mk.i" : 200890,
"tf_weapon_minigun" : 891,
"blood botkiller minigun mk.i" : 200891,
"tf_weapon_knife" : 892,
"blood botkiller knife mk.i" : 200892,
"tf_weapon_wrench" : 893,
"blood botkiller wrench mk.i" : 200893,
"tf_weapon_medigun" : 894,
"blood botkiller medi gun mk.i" : 200894,
"tf_weapon_pipebomblauncher" : 895,
"blood botkiller stickybomb launcher mk.i" : 200895,
"tf_weapon_flamethrower" : 896,
"blood botkiller flame thrower mk.i" : 200896,
"tf_weapon_scattergun" : 897,
"blood botkiller scattergun mk.i" : 200897,
"tf_weapon_rocketlauncher" : 898,
"blood botkiller rocket launcher mk.i" : 200898,
"tf_weapon_sniperrifle" : 899,
"carbonado botkiller sniper rifle mk.i" : 200899,
"tf_weapon_minigun" : 900,
"carbonado botkiller minigun mk.i" : 200900,
"tf_weapon_knife" : 901,
"carbonado botkiller knife mk.i" : 200901,
"tf_weapon_wrench" : 902,
"carbonado botkiller wrench mk.i" : 200902,
"tf_weapon_medigun" : 903,
"carbonado botkiller medi gun mk.i" : 200903,
"tf_weapon_pipebomblauncher" : 904,
"carbonado botkiller stickybomb launcher mk.i" : 200904,
"tf_weapon_flamethrower" : 905,
"carbonado botkiller flame thrower mk.i" : 200905,
"tf_weapon_scattergun" : 906,
"carbonado botkiller scattergun mk.i" : 200906,
"tf_weapon_rocketlauncher" : 907,
"carbonado botkiller rocket launcher mk.i" : 200907,
"tf_weapon_sniperrifle" : 908,
"diamond botkiller sniper rifle mk.i" : 200908,
"tf_weapon_minigun" : 909,
"diamond botkiller minigun mk.i" : 200909,
"tf_weapon_knife" : 910,
"diamond botkiller knife mk.i" : 200910,
"tf_weapon_wrench" : 911,
"diamond botkiller wrench mk.i" : 200911,
"tf_weapon_medigun" : 912,
"diamond botkiller medi gun mk.i" : 200912,
"tf_weapon_pipebomblauncher" : 913,
"diamond botkiller stickybomb launcher mk.i" : 200913,
"tf_weapon_flamethrower" : 914,
"diamond botkiller flame thrower mk.i" : 200914,
"tf_weapon_scattergun" : 915,
"diamond botkiller scattergun mk.i" : 200915,
"tf_weapon_rocketlauncher" : 916,
"diamond botkiller rocket launcher mk.i" : 200916,
"tf_weapon_sapper" : 933,
"the ap-sap" : 200933,
"tf_weapon_invis" : 947,
"the quackenbirdt" : 200947,
"tf_weapon_sniperrifle" : 957,
"silver botkiller sniper rifle mk.ii" : 200957,
"tf_weapon_minigun" : 958,
"silver botkiller minigun mk.ii" : 200958,
"tf_weapon_knife" : 959,
"silver botkiller knife mk.ii" : 200959,
"tf_weapon_wrench" : 960,
"silver botkiller wrench mk.ii" : 200960,
"tf_weapon_medigun" : 961,
"silver botkiller medi gun mk.ii" : 200961,
"tf_weapon_pipebomblauncher" : 962,
"silver botkiller stickybomb launcher mk.ii" : 200962,
"tf_weapon_flamethrower" : 963,
"silver botkiller flame thrower mk.ii" : 200963,
"tf_weapon_scattergun" : 964,
"silver botkiller scattergun mk.ii" : 200964,
"tf_weapon_rocketlauncher" : 965,
"silver botkiller rocket launcher mk.ii" : 200965,
"tf_weapon_sniperrifle" : 966,
"gold botkiller sniper rifle mk.ii" : 200966,
"tf_weapon_minigun" : 967,
"gold botkiller minigun mk.ii" : 200967,
"tf_weapon_knife" : 968,
"gold botkiller knife mk.ii" : 200968,
"tf_weapon_wrench" : 969,
"gold botkiller wrench mk.ii" : 200969,
"tf_weapon_medigun" : 970,
"gold botkiller medi gun mk.ii" : 200970,
"tf_weapon_pipebomblauncher" : 971,
"gold botkiller stickybomb launcher mk.ii" : 200971,
"tf_weapon_flamethrower" : 972,
"gold botkiller flame thrower mk.ii" : 200972,
"tf_weapon_scattergun" : 973,
"gold botkiller scattergun mk.ii" : 200973,
"tf_weapon_rocketlauncher" : 974,
"gold botkiller rocket launcher mk.ii" : 200974,
"tf_weapon_cannon" : 996,
"the loose cannon" : 200996,
"tf_weapon_shotgun_building_rescue" : 997,
"the rescue ranger" : 200997,
"tf_weapon_medigun" : 998,
"the vaccinator" : 200998,
"tf_weapon_bat_fish" : 999,
"festive holy mackerel" : 200999,
"tf_weapon_fireaxe" : 1000,
"the festive axtinguisher" : 201000,
"tf_weapon_buff_item" : 1001,
"festive buff banner" : 201001,
"tf_weapon_lunchbox" : 1002,
"festive sandvich" : 201002,
"tf_weapon_bonesaw" : 1003,
"festive ubersaw" : 201003,
"tf_weapon_sentry_revenge" : 1004,
"festive frontier justice" : 201004,
"tf_weapon_compound_bow" : 1005,
"festive huntsman" : 201005,
"tf_weapon_revolver" : 1006,
"festive ambassador" : 201006,
"tf_weapon_grenadelauncher" : 1007,
"festive grenade launcher" : 201007,
"tf_weapon_spellbook" : 1069,
"fancy spellbook" : 201069,
"tf_weapon_spellbook" : 1070,
"spellbook magazine" : 201070,
"tf_weapon_scattergun" : 1078,
"festive force-a-nature" : 201078,
"tf_weapon_crossbow" : 1079,
"festive crusader's crossbow" : 201079,
"tf_weapon_sapper" : 1080,
"festive sapper" : 201080,
"tf_weapon_flaregun" : 1081,
"festive flare gun" : 201081,
"tf_weapon_sword" : 1082,
"festive eyelander" : 201082,
"tf_weapon_jar" : 1083,
"festive jarate" : 201083,
"tf_weapon_fists" : 1084,
"festive gloves of running urgently" : 201084,
"tf_weapon_rocketlauncher" : 1085,
"festive black box" : 201085,
"tf_weapon_laser_pointer" : 1086,
"festive wrangler" : 201086,
"tf_weapon_compound_bow" : 1092,
"the fortified compound" : 201092,
"tf_weapon_sniperrifle_classic" : 1098,
"the classic" : 201098,
"tf_wearable_demoshield" : 1099,
"the tide turner" : 201099,
"tf_weapon_fists" : 1100,
"the bread bite" : 201100,
"tf_weapon_parachute" : 1101,
"the b.a.s.e. jumper" : 201101,
"tf_weapon_sapper" : 1102,
"the snack attack" : 201102,
"tf_weapon_scattergun" : 1103,
"the back scatter" : 201103,
"tf_weapon_rocketlauncher_airstrike" : 1104,
"the air strike" : 201104,
"tf_weapon_jar" : 1105,
"the self-aware beauty mark" : 201105,
"tf_weapon_jar_milk" : 1121,
"mutated milk" : 201121,
"tf_weapon_spellbook" : 1132,
"spellbook magazine" : 201132,
"tf_weapon_shotgun" : 1141,
"festive shotgun" : 201141,
"tf_weapon_revolver" : 1142,
"festive revolver" : 201142,
"tf_weapon_bonesaw" : 1143,
"festive bonesaw" : 201143,
"tf_wearable_demoshield" : 1144,
"festive targe" : 201144,
"tf_weapon_lunchbox_drink" : 1145,
"festive bonk!" : 201145,
"tf_weapon_flamethrower" : 1146,
"festive backburner" : 201146,
"tf_weapon_smg" : 1149,
"festive smg" : 201149,
"tf_weapon_pipebomblauncher" : 1150,
"the quickiebomb launcher" : 201150,
"tf_weapon_grenadelauncher" : 1151,
"the iron bomber" : 201151,
"tf_weapon_grapplinghook" : 1152,
"grappling hook" : 201152,
"tf_weapon_shotgun" : 1153,
"panic attack" : 201153,
"tf_weapon_rocketlauncher_fireball" : 1178,
"dragon's fury" : 201178,
"tf_weapon_rocketpack" : 1179,
"thermal thruster" : 201179,
"tf_weapon_jar_gas" : 1180,
"gas passer" : 201180,
"tf_weapon_slap" : 1181,
"hot hand" : 201181,
"tf_weapon_fists" : 1184,
"gloves of running urgently mvm" : 201184,
"tf_weapon_lunchbox" : 1190,
"second banana" : 201190,
"tf_weapon_spellbook" : 5605,
"fireproof secret diary" : 205605,
"tf_weapon_sniperrifle" : 15000,
"night owl" : 215000,
"tf_weapon_smg" : 15001,
"woodsy widowmaker" : 215001,
"tf_weapon_scattergun" : 15002,
"night terror" : 215002,
"tf_weapon_shotgun" : 15003,
"backwoods boomstick" : 215003,
"tf_weapon_minigun" : 15004,
"king of the jungle" : 215004,
"tf_weapon_flamethrower" : 15005,
"forest fire" : 215005,
"tf_weapon_rocketlauncher" : 15006,
"woodland warrior" : 215006,
"tf_weapon_sniperrifle" : 15007,
"purple range" : 215007,
"tf_weapon_medigun" : 15008,
"masked mender" : 215008,
"tf_weapon_pipebomblauncher" : 15009,
"sudden flurry" : 215009,
"tf_weapon_medigun" : 15010,
"wrapped reviver" : 215010,
"tf_weapon_revolver" : 15011,
"psychedelic slugger" : 215011,
"tf_weapon_pipebomblauncher" : 15012,
"carpet bomber" : 215012,
"tf_weapon_pistol" : 15013,
"red rock roscoe" : 215013,
"tf_weapon_rocketlauncher" : 15014,
"sand cannon" : 215014,
"tf_weapon_scattergun" : 15015,
"tartan torpedo" : 215015,
"tf_weapon_shotgun" : 15016,
"rustic ruiner" : 215016,
"tf_weapon_flamethrower" : 15017,
"barn burner" : 215017,
"tf_weapon_pistol" : 15018,
"homemade heater" : 215018,
"tf_weapon_sniperrifle" : 15019,
"lumber from down under" : 215019,
"tf_weapon_minigun" : 15020,
"iron wood" : 215020,
"tf_weapon_scattergun" : 15021,
"country crusher" : 215021,
"tf_weapon_smg" : 15022,
"plaid potshotter" : 215022,
"tf_weapon_sniperrifle" : 15023,
"shot in the dark" : 215023,
"tf_weapon_pipebomblauncher" : 15024,
"blasted bombardier" : 215024,
"tf_weapon_medigun" : 15025,
"reclaimed reanimator" : 215025,
"tf_weapon_minigun" : 15026,
"antique annihilator" : 215026,
"tf_weapon_revolver" : 15027,
"old country" : 215027,
"tf_weapon_rocketlauncher" : 15028,
"american pastoral" : 215028,
"tf_weapon_scattergun" : 15029,
"backcountry blaster" : 215029,
"tf_weapon_flamethrower" : 15030,
"bovine blazemaker" : 215030,
"tf_weapon_minigun" : 15031,
"war room" : 215031,
"tf_weapon_smg" : 15032,
"treadplate tormenter" : 215032,
"tf_weapon_sniperrifle" : 15033,
"bogtrotter" : 215033,
"tf_weapon_flamethrower" : 15034,
"earth, sky and fire" : 215034,
"tf_weapon_pistol" : 15035,
"hickory holepuncher" : 215035,
"tf_weapon_scattergun" : 15036,
"spruce deuce" : 215036,
"tf_weapon_smg" : 15037,
"team sprayer" : 215037,
"tf_weapon_pipebomblauncher" : 15038,
"rooftop wrangler" : 215038,
"tf_weapon_medigun" : 15039,
"civil servant" : 215039,
"tf_weapon_minigun" : 15040,
"citizen pain" : 215040,
"tf_weapon_pistol" : 15041,
"local hero" : 215041,
"tf_weapon_revolver" : 15042,
"mayor" : 215042,
"tf_weapon_rocketlauncher" : 15043,
"smalltown bringdown" : 215043,
"tf_weapon_shotgun" : 15044,
"civic duty" : 215044,
"tf_weapon_pipebomblauncher" : 15045,
"liquid asset" : 215045,
"tf_weapon_pistol" : 15046,
"black dahlia" : 215046,
"tf_weapon_shotgun" : 15047,
"lightning rod" : 215047,
"tf_weapon_pipebomblauncher" : 15048,
"pink elephant" : 215048,
"tf_weapon_flamethrower" : 15049,
"flash fryer" : 215049,
"tf_weapon_medigun" : 15050,
"spark of life" : 215050,
"tf_weapon_revolver" : 15051,
"dead reckoner" : 215051,
"tf_weapon_rocketlauncher" : 15052,
"shell shocker" : 215052,
"tf_weapon_scattergun" : 15053,
"current event" : 215053,
"tf_weapon_flamethrower" : 15054,
"turbine torcher" : 215054,
"tf_weapon_minigun" : 15055,
"brick house" : 215055,
"tf_weapon_pistol" : 15056,
"sandstone special" : 215056,
"tf_weapon_rocketlauncher" : 15057,
"aqua marine" : 215057,
"tf_weapon_smg" : 15058,
"low profile" : 215058,
"tf_weapon_sniperrifle" : 15059,
"thunderbolt" : 215059,
"tf_weapon_pistol" : 15060,
"macabre web" : 215060,
"tf_weapon_pistol" : 15061,
"nutcracker" : 215061,
"tf_weapon_revolver" : 15062,
"boneyard" : 215062,
"tf_weapon_knife" : 15062,
"tf_weapon_revolver" : 15063,
"wildwood" : 215063,
"tf_weapon_revolver" : 15064,
"macabre web" : 215064,
"tf_weapon_scattergun" : 15065,
"macabre web" : 215065,
"tf_weapon_flamethrower" : 15066,
"autumn" : 215066,
"tf_weapon_flamethrower" : 15067,
"pumpkin patch" : 215067,
"tf_weapon_flamethrower" : 15068,
"nutcracker" : 215068,
"tf_weapon_scattergun" : 15069,
"nutcracker" : 215069,
"tf_weapon_sniperrifle" : 15070,
"pumpkin patch" : 215070,
"tf_weapon_sniperrifle" : 15071,
"boneyard" : 215071,
"tf_weapon_sniperrifle" : 15072,
"wildwood" : 215072,
"tf_weapon_wrench" : 15073,
"nutcracker" : 215073,
"tf_weapon_wrench" : 15074,
"autumn" : 215074,
"tf_weapon_wrench" : 15075,
"boneyard" : 215075,
"tf_weapon_smg" : 15076,
"wildwood" : 215076,
"tf_weapon_grenadelauncher" : 15077,
"autumn" : 215077,
"tf_weapon_medigun" : 15078,
"wildwood" : 215078,
"tf_weapon_grenadelauncher" : 15079,
"macabre web" : 215079,
"tf_weapon_rocketlauncher" : 15081,
"autumn" : 215081,
"tf_weapon_pipebomblauncher" : 15082,
"autumn" : 215082,
"tf_weapon_pipebomblauncher" : 15083,
"pumpkin patch" : 215083,
"tf_weapon_pipebomblauncher" : 15084,
"macabre web" : 215084,
"tf_weapon_shotgun" : 15085,
"autumn" : 215085,
"tf_weapon_minigun" : 15086,
"macabre web" : 215086,
"tf_weapon_minigun" : 15087,
"pumpkin patch" : 215087,
"tf_weapon_minigun" : 15088,
"nutcracker" : 215088,
"tf_weapon_flamethrower" : 15089,
"balloonicorn" : 215089,
"tf_weapon_flamethrower" : 15090,
"rainbow" : 215090,
"tf_weapon_grenadelauncher" : 15091,
"rainbow" : 215091,
"tf_weapon_grenadelauncher" : 15092,
"sweet dreams" : 215092,
"tf_weapon_knife" : 15094,
"blue mew" : 215094,
"tf_weapon_knife" : 15095,
"brain candy" : 215095,
"tf_weapon_knife" : 15096,
"stabbed to hell" : 215096,
"tf_weapon_medigun" : 15097,
"flower power" : 215097,
"tf_weapon_minigun" : 15098,
"brain candy" : 215098,
"tf_weapon_minigun" : 15099,
"mister cuddles" : 215099,
"tf_weapon_pistol" : 15100,
"blue mew" : 215100,
"tf_weapon_pistol" : 15101,
"brain candy" : 215101,
"tf_weapon_pistol" : 15102,
"shot to hell" : 215102,
"tf_weapon_revolver" : 15103,
"flower power" : 215103,
"tf_weapon_rocketlauncher" : 15104,
"blue mew" : 215104,
"tf_weapon_rocketlauncher" : 15105,
"brain candy" : 215105,
"tf_weapon_scattergun" : 15106,
"blue mew" : 215106,
"tf_weapon_scattergun" : 15107,
"flower power" : 215107,
"tf_weapon_scattergun" : 15108,
"shot to hell" : 215108,
"tf_weapon_shotgun" : 15109,
"flower power" : 215109,
"tf_weapon_smg" : 15110,
"blue mew" : 215110,
"tf_weapon_sniperrifle" : 15111,
"balloonicorn" : 215111,
"tf_weapon_sniperrifle" : 15112,
"rainbow" : 215112,
"tf_weapon_pipebomblauncher" : 15113,
"sweet dreams" : 215113,
"tf_weapon_wrench" : 15114,
"torqued to hell" : 215114,
"tf_weapon_flamethrower" : 15115,
"coffin nail" : 215115,
"tf_weapon_grenadelauncher" : 15116,
"coffin nail" : 215116,
"tf_weapon_grenadelauncher" : 15117,
"top shelf" : 215117,
"tf_weapon_knife" : 15118,
"dressed to kill" : 215118,
"tf_weapon_knife" : 15119,
"top shelf" : 215119,
"tf_weapon_medigun" : 15121,
"dressed to kill" : 215121,
"tf_weapon_medigun" : 15122,
"high roller's" : 215122,
"tf_weapon_minigun" : 15123,
"coffin nail" : 215123,
"tf_weapon_medigun" : 15123,
"tf_weapon_minigun" : 15124,
"dressed to kill" : 215124,
"tf_weapon_minigun" : 15125,
"top shelf" : 215125,
"tf_weapon_pistol" : 15126,
"dressed to kill" : 215126,
"tf_weapon_revolver" : 15127,
"coffin nail" : 215127,
"tf_weapon_revolver" : 15128,
"top shelf" : 215128,
"tf_weapon_rocketlauncher" : 15129,
"coffin nail" : 215129,
"tf_weapon_rocketlauncher" : 15130,
"high roller's" : 215130,
"tf_weapon_scattergun" : 15131,
"coffin nail" : 215131,
"tf_weapon_shotgun" : 15132,
"coffin nail" : 215132,
"tf_weapon_shotgun" : 15133,
"dressed to kill" : 215133,
"tf_weapon_smg" : 15134,
"high roller's" : 215134,
"tf_weapon_sniperrifle" : 15135,
"coffin nail" : 215135,
"tf_weapon_sniperrifle" : 15136,
"dressed to kill" : 215136,
"tf_weapon_pipebomblauncher" : 15137,
"coffin nail" : 215137,
"tf_weapon_pipebomblauncher" : 15138,
"dressed to kill" : 215138,
"tf_weapon_wrench" : 15139,
"dressed to kill" : 215139,
"tf_weapon_wrench" : 15140,
"top shelf" : 215140,
"tf_weapon_flamethrower" : 15141,
"warhawk" : 215141,
"tf_weapon_grenadelauncher" : 15142,
"warhawk" : 215142,
"tf_weapon_knife" : 15143,
"blitzkrieg" : 215143,
"tf_weapon_knife" : 15144,
"airwolf" : 215144,
"tf_weapon_medigun" : 15145,
"blitzkrieg" : 215145,
"tf_weapon_medigun" : 15146,
"corsair" : 215146,
"tf_weapon_minigun" : 15147,
"butcher bird" : 215147,
"tf_weapon_pistol" : 15148,
"blitzkrieg" : 215148,
"tf_weapon_revolver" : 15149,
"blitzkrieg" : 215149,
"tf_weapon_rocketlauncher" : 15150,
"warhawk" : 215150,
"tf_weapon_scattergun" : 15151,
"killer bee" : 215151,
"tf_weapon_shotgun" : 15152,
"red bear" : 215152,
"tf_weapon_smg" : 15153,
"blitzkrieg" : 215153,
"tf_weapon_sniperrifle" : 15154,
"airwolf" : 215154,
"tf_weapon_pipebomblauncher" : 15155,
"blitzkrieg" : 215155,
"tf_weapon_wrench" : 15156,
"airwolf" : 215156,
"tf_weapon_scattergun" : 15157,
"corsair" : 215157,
"tf_weapon_grenadelauncher" : 15158,
"butcher bird" : 215158,
"tf_powerup_bottle" : 30015,
"battery canteens" : 230015,
"tf_weapon_flamethrower" : 30474,
"nostromo napalmer" : 230474,
"tf_powerup_bottle" : 30535,
"kritz or treat canteen" : 230535,
"tf_weapon_sniperrifle" : 30665,
"shooting star" : 230665,
"tf_weapon_pistol" : 30666,
"the c.a.p.p.e.r." : 230666,
"tf_weapon_bat" : 30667,
"batsaber" : 230667,
"tf_weapon_laser_pointer" : 30668,
"the gigar counter" : 230668,
}

propdict = {
"m_flAnimTime": "integer",
"m_flSimulationTime": "integer",
"m_vecOrigin": "vector",
"m_ubInterpolationFrame": "integer",
"m_nModelIndex": "integer",
"m_vecMinsPreScaled": "vector",
"m_vecMaxsPreScaled": "vector",
"m_vecMins": "vector",
"m_vecMaxs": "vector",
"m_nSolidType": "integer",
"m_usSolidFlags": "integer",
"m_nSurroundType": "integer",
"m_triggerBloat": "integer",
"m_bUniformTriggerBloat": "integer",
"m_vecSpecifiedSurroundingMinsPreScaled": "vector",
"m_vecSpecifiedSurroundingMaxsPreScaled": "vector",
"m_vecSpecifiedSurroundingMins": "vector",
"m_vecSpecifiedSurroundingMaxs": "vector",
"m_nRenderFX": "integer",
"m_nRenderMode": "integer",
"m_fEffects": "integer",
"m_clrRender": "integer",
"m_iTeamNum": "integer",
"m_CollisionGroup": "integer",
"m_flElasticity": "float",
"m_flShadowCastDistance": "float",
"m_hOwnerEntity": "integer",
"m_hEffectEntity": "integer",
"m_iParentAttachment": "integer",
"m_angRotation": "vector",
"m_iTextureFrameIndex": "integer",
"m_PredictableID": "integer",
"m_bIsPlayerSimulated": "integer",
"m_bSimulatedEveryTick": "integer",
"m_bAnimatedEveryTick": "integer",
"m_bAlternateSorting": "integer",
"m_nForceBone": "integer",
"m_vecForce": "vector",
"m_nSkin": "integer",
"m_nBody": "integer",
"m_nHitboxSet": "integer",
"m_flModelScale": "float",
"m_nSequence": "integer",
"m_flPlaybackRate": "float",
"m_bClientSideAnimation": "integer",
"m_bClientSideFrameReset": "integer",
"m_nNewSequenceParity": "integer",
"m_nResetEventsParity": "integer",
"m_nMuzzleFlashParity": "integer",
"m_hLightingOrigin": "integer",
"m_hLightingOriginRelative": "integer",
"m_flCycle": "float",
"m_fadeMinDist": "float",
"m_fadeMaxDist": "float",
"m_flFadeScale": "float",
"m_flPrevCycle": "float",
"m_flWeight": "float",
"m_nOrder": "integer",
"m_blinktoggle": "integer",
"m_viewtarget": "vector",
"m_bGlowEnabled": "integer",
"m_flNextAttack": "float",
"m_hActiveWeapon": "integer",
"m_lifeState": "integer",
"m_bPerformAvoidance": "integer",
"m_bIsMoving": "integer",
"m_bFadeCorpse": "integer",
"m_iDeathPose": "integer",
"m_iDeathFrame": "integer",
"m_bSpeedModActive": "integer",
"m_iSpeedModRadius": "integer",
"m_iSpeedModSpeed": "integer",
"m_bImportanRagdoll": "integer",
"m_flTimePingEffect": "float",
"m_hOuter": "integer",
"m_ProviderType": "integer",
"m_iReapplyProvisionParity": "integer",
"m_iItemDefinitionIndex": "integer",
"m_iEntityLevel": "integer",
"m_iItemIDHigh": "integer",
"m_iItemIDLow": "integer",
"m_iAccountID": "integer",
"m_iEntityQuality": "integer",
"m_bInitialized": "integer",
"m_bOnlyIterateItemViewAttributes": "integer",
"m_iAttributeDefinitionIndex": "integer",
"m_iRawValue32": "integer",
"m_nRefundableCurrency": "integer",
"m_iTeamNumber": "integer",
"m_bValidatedAttachedEntity": "integer",
"m_iClip1": "integer",
"m_iClip2": "integer",
"m_iPrimaryAmmoType": "integer",
"m_iSecondaryAmmoType": "integer",
"m_nViewModelIndex": "integer",
"m_nCustomViewmodelModelIndex": "integer",
"m_bFlipViewModel": "integer",
"m_flNextPrimaryAttack": "float",
"m_flNextSecondaryAttack": "float",
"m_nNextThinkTick": "integer",
"m_flTimeWeaponIdle": "float",
"m_iViewModelIndex": "integer",
"m_iWorldModelIndex": "integer",
"m_iState": "integer",
"m_hOwner": "integer",
"m_flWaveHeight": "float",
"m_hOriginalLauncher": "integer",
"m_flDamage": "float",
"m_DmgRadius": "float",
"m_bIsLive": "integer",
"m_hThrower": "integer",
"m_vecVelocity": "vector",
"m_fFlags": "integer",
"m_iHealth": "integer",
"m_iMaxHealth": "integer",
"m_bHasSapper": "integer",
"m_iObjectType": "integer",
"m_bBuilding": "integer",
"m_bPlacing": "integer",
"m_bCarried": "integer",
"m_bCarryDeploy": "integer",
"m_bMiniBuilding": "integer",
"m_flPercentageConstructed": "float",
"m_fObjectFlags": "integer",
"m_hBuiltOnEntity": "integer",
"m_bDisabled": "integer",
"m_hBuilder": "integer",
"m_vecBuildMaxs": "vector",
"m_vecBuildMins": "vector",
"m_iDesiredBuildRotations": "integer",
"m_bServerOverridePlacement": "integer",
"m_iUpgradeLevel": "integer",
"m_iUpgradeMetal": "integer",
"m_iUpgradeMetalRequired": "integer",
"m_iHighestUpgradeLevel": "integer",
"m_iObjectMode": "integer",
"m_bDisposableBuilding": "integer",
"m_bWasMapPlaced": "integer",
"m_bPlasmaDisable": "integer",
"m_hVehicle": "integer",
"m_hUseEntity": "integer",
"m_iBonusProgress": "integer",
"m_iBonusChallenge": "integer",
"m_flMaxspeed": "float",
"m_iObserverMode": "integer",
"m_hObserverTarget": "integer",
"m_iFOV": "integer",
"m_iFOVStart": "integer",
"m_flFOVTime": "float",
"m_iDefaultFOV": "integer",
"m_hZoomOwner": "integer",
"m_hViewModel": "array",
"m_szLastPlaceName": "string",
"m_iHideHUD": "integer",
"m_flFOVRate": "float",
"m_bDucked": "integer",
"m_bDucking": "integer",
"m_bInDuckJump": "integer",
"m_flDucktime": "float",
"m_flDuckJumpTime": "float",
"m_flJumpTime": "float",
"m_flFallVelocity": "float",
"m_vecPunchAngle": "vector",
"m_vecPunchAngleVel": "vector",
"m_bDrawViewmodel": "integer",
"m_bWearingSuit": "integer",
"m_bPoisoned": "integer",
"m_bForceLocalPlayerDraw": "integer",
"m_flStepSize": "float",
"m_bAllowAutoMovement": "integer",
"m_skybox3d.scale": "integer",
"m_skybox3d.origin": "vector",
"m_skybox3d.area": "integer",
"m_skybox3d.fog.enable": "integer",
"m_skybox3d.fog.blend": "integer",
"m_skybox3d.fog.dirPrimary": "vector",
"m_skybox3d.fog.colorPrimary": "integer",
"m_skybox3d.fog.colorSecondary": "integer",
"m_skybox3d.fog.start": "float",
"m_skybox3d.fog.end": "float",
"m_skybox3d.fog.maxdensity": "float",
"m_PlayerFog.m_hCtrl": "integer",
"m_audio.localSound[0]": "vector",
"m_audio.localSound[1]": "vector",
"m_audio.localSound[2]": "vector",
"m_audio.localSound[3]": "vector",
"m_audio.localSound[4]": "vector",
"m_audio.localSound[5]": "vector",
"m_audio.localSound[6]": "vector",
"m_audio.localSound[7]": "vector",
"m_audio.soundscapeIndex": "integer",
"m_audio.localBits": "integer",
"m_audio.entIndex": "integer",
"m_szScriptOverlayMaterial": "string",
"m_vecViewOffset[0]": "float",
"m_vecViewOffset[1]": "float",
"m_vecViewOffset[2]": "float",
"m_flFriction": "float",
"m_fOnTarget": "integer",
"m_nTickBase": "integer",
"m_hLastWeapon": "integer",
"m_hGroundEntity": "integer",
"m_vecVelocity[0]": "float",
"m_vecVelocity[1]": "float",
"m_vecVelocity[2]": "float",
"m_vecBaseVelocity": "vector",
"m_hConstraintEntity": "integer",
"m_vecConstraintCenter": "vector",
"m_flConstraintRadius": "float",
"m_flConstraintWidth": "float",
"m_flConstraintSpeedFactor": "float",
"m_flDeathTime": "float",
"m_nWaterLevel": "integer",
"m_flLaggedMovementValue": "float",
"m_bUseHitboxesForRenderBox": "integer",
"m_iTimerToShowInHUD": "integer",
"m_iStopWatchTimer": "integer",
"m_iNumControlPoints": "integer",
"m_bPlayingMiniRounds": "integer",
"m_bControlPointsReset": "integer",
"m_iUpdateCapHudParity": "integer",
"m_vCPPositions": "array",
"m_iszWarnSound": "array",
"m_pszCapLayoutInHUD": "string",
"m_flCustomPositionX": "float",
"m_flCustomPositionY": "float",
"m_nAnimationParity": "integer",
"m_hWeapon": "integer",
"m_flPoseParameter": "array",
"m_nBeamType": "integer",
"m_nBeamFlags": "integer",
"m_nNumBeamEnts": "integer",
"m_nHaloIndex": "integer",
"m_fHaloScale": "float",
"m_fWidth": "float",
"m_fEndWidth": "float",
"m_fFadeLength": "float",
"m_fAmplitude": "float",
"m_fStartFrame": "float",
"m_fSpeed": "float",
"m_flFrameRate": "float",
"m_flHDRColorScale": "float",
"m_flFrame": "float",
"m_vecEndPos": "vector",
"m_nMinDXLevel": "integer",
"m_modelIndex": "integer",
"m_solidIndex": "integer",
"m_bSpecial": "integer",
"m_bDistributed": "integer",
"m_hBonusWinner": "integer",
"m_nNumWide": "integer",
"m_nNumHigh": "integer",
"m_flPanelWidth": "float",
"m_flPanelHeight": "float",
"m_vNormal": "vector",
"m_vCorner": "vector",
"m_bIsBroken": "integer",
"m_nSurfaceType": "integer",
"m_bVisibleWhenDisabled": "integer",
"m_nType": "integer",
"m_nFlagStatus": "integer",
"m_flResetTime": "float",
"m_flNeutralTime": "float",
"m_flMaxResetTime": "float",
"m_hPrevOwner": "integer",
"m_szModel": "string",
"m_szHudIcon": "string",
"m_szPaperEffect": "string",
"m_szTrailEffect": "string",
"m_nUseTrailEffect": "integer",
"m_nPointValue": "integer",
"m_flAutoCapTime": "float",
"m_flTimeToSetPoisonous": "float",
"m_MinFalloff": "float",
"m_MaxFalloff": "float",
"m_flCurWeight": "float",
"m_netlookupFilename": "string",
"m_bEnabled": "integer",
"m_Weight": "float",
"m_lookupFilename": "string",
"m_Flags": "integer",
"m_LightStyle": "integer",
"m_Radius": "float",
"m_Exponent": "integer",
"m_InnerAngle": "float",
"m_OuterAngle": "float",
"m_SpotRadius": "float",
"m_nDensity": "integer",
"m_nLifetime": "integer",
"m_nSpeed": "integer",
"m_bEmit": "integer",
"m_flStartTime": "float",
"m_flFadeInStart": "float",
"m_flFadeInLength": "float",
"m_flFadeOutModelStart": "float",
"m_flFadeOutModelLength": "float",
"m_flFadeOutStart": "float",
"m_flFadeOutLength": "float",
"m_nDissolveType": "integer",
"m_vDissolverOrigin": "vector",
"m_nMagnitude": "integer",
"m_hEntAttached": "integer",
"m_iMaterialName": "integer",
"m_flLifetime": "float",
"m_flStartSize": "float",
"m_flEndSize": "float",
"m_flFadeStartDist": "float",
"m_flFadeEndDist": "float",
"m_flSequenceScale": "float",
"m_hTargetEntity": "integer",
"m_bState": "integer",
"m_flLightFOV": "float",
"m_bEnableShadows": "integer",
"m_bLightOnlyTarget": "integer",
"m_bLightWorld": "integer",
"m_bCameraSpace": "integer",
"m_LinearFloatLightColor": "vector",
"m_flAmbient": "float",
"m_SpotlightTextureName": "string",
"m_nSpotlightTextureFrame": "integer",
"m_flNearZ": "float",
"m_flFarZ": "float",
"m_nShadowQuality": "integer",
"m_targetPosition": "vector",
"m_controlPosition": "vector",
"m_scrollRate": "float",
"m_flWidth": "float",
"m_flDuration": "float",
"m_iszOverlayNames": "array",
"m_flOverlayTimes": "array",
"m_iDesiredOverlay": "integer",
"m_bIsActive": "integer",
"m_bUseCustomAutoExposureMin": "integer",
"m_bUseCustomAutoExposureMax": "integer",
"m_bUseCustomBloomScale": "integer",
"m_flCustomAutoExposureMin": "float",
"m_flCustomAutoExposureMax": "float",
"m_flCustomBloomScale": "float",
"m_flCustomBloomScaleMinimum": "float",
"m_iMinWind": "integer",
"m_iMaxWind": "integer",
"m_iMinGust": "integer",
"m_iMaxGust": "integer",
"m_flMinGustDelay": "float",
"m_flMaxGustDelay": "float",
"m_iGustDirChange": "integer",
"m_iWindSeed": "integer",
"m_iInitialWindDir": "integer",
"m_flInitialWindSpeed": "float",
"m_flGustDuration": "float",
"m_angAbsRotation": "integer",
"m_lookAtSpot": "vector",
"m_attitude": "integer",
"m_flStartScale": "float",
"m_flScale": "float",
"m_flScaleTime": "float",
"m_nFlags": "integer",
"m_nFlameModelIndex": "integer",
"m_nFlameFromAboveModelIndex": "integer",
"m_nAttachment": "integer",
"m_poolOrigin": "vector",
"m_angle": "float",
"m_x": "float",
"m_y": "float",
"m_z": "float",
"m_waterLevel": "float",
"m_fog.enable": "integer",
"m_fog.blend": "integer",
"m_fog.dirPrimary": "vector",
"m_fog.colorPrimary": "integer",
"m_fog.colorSecondary": "integer",
"m_fog.start": "float",
"m_fog.end": "float",
"m_fog.maxdensity": "float",
"m_fog.farz": "float",
"m_fog.colorPrimaryLerpTo": "integer",
"m_fog.colorSecondaryLerpTo": "integer",
"m_fog.startLerpTo": "float",
"m_fog.endLerpTo": "float",
"m_fog.lerptime": "float",
"m_fog.duration": "float",
"m_Color": "vector",
"m_SpawnRate": "float",
"m_SpeedMax": "integer",
"m_flSizeMin": "float",
"m_flSizeMax": "float",
"m_DistMax": "integer",
"m_LifetimeMin": "integer",
"m_LifetimeMax": "integer",
"m_DustFlags": "integer",
"m_FallSpeed": "float",
"m_fDisappearDist": "float",
"m_flFadeDist": "float",
"m_flTranslucencyLimit": "float",
"m_iBackgroundModelIndex": "integer",
"m_flConveyorSpeed": "float",
"m_vecPlayerMountPositionTop": "vector",
"m_vecPlayerMountPositionBottom": "vector",
"m_vecLadderDir": "vector",
"m_bFakeLadder": "integer",
"m_bActive": "integer",
"m_nOccluderIndex": "integer",
"m_bTriggerDisabled": "integer",
"m_iGoalType": "integer",
"m_angRotation[0]": "float",
"m_angRotation[1]": "float",
"m_angRotation[2]": "float",
"m_Color1": "integer",
"m_Color2": "integer",
"m_MaterialName": "string",
"m_ParticleDrawWidth": "float",
"m_ParticleSpacingDistance": "float",
"m_DensityRampSpeed": "float",
"m_RotationSpeed": "float",
"m_MovementSpeed": "float",
"m_Density": "float",
"m_spawnflags": "integer",
"m_hTargetPlayer": "integer",
"m_hTarget": "integer",
"m_vecPreCurvePos": "vector",
"m_vecStartCurvePos": "vector",
"m_Handle": "integer",
"m_bSendHandle": "integer",
"m_hLightingLandmark": "integer",
"m_iOverlayID": "integer",
"m_flChargeStartTime": "float",
"m_nHorizontalSize": "integer",
"m_nVerticalSize": "integer",
"m_nMinDist": "integer",
"m_nMaxDist": "integer",
"m_nOuterMaxDist": "integer",
"m_flGlowProxySize": "float",
"m_iCurrentWaveIdx": "integer",
"m_iServerWaveID": "integer",
"m_iCurrencyCollectedForRespec": "integer",
"m_nRespecsAwardedInWave": "integer",
"m_szMaterialName": "string",
"m_szMaterialVar": "string",
"m_szMaterialVarValue": "string",
"m_iFrameStart": "integer",
"m_iFrameEnd": "integer",
"m_bWrap": "integer",
"m_flFramerate": "float",
"m_bNewAnimCommandsSemaphore": "integer",
"m_flFloatLerpStartValue": "float",
"m_flFloatLerpEndValue": "float",
"m_flFloatLerpTransitionTime": "float",
"m_nModifyMode": "integer",
"m_bRevealed": "integer",
"m_bIsDoingAOEAttack": "integer",
"m_bStunned": "integer",
"m_iBossHealthPercentageByte": "integer",
"m_iBossStunPercentageByte": "integer",
"m_iSkillShotCompleteCount": "integer",
"m_fSkillShotComboEndTime": "float",
"m_iBossState": "integer",
"m_iAmmoMetal": "integer",
"m_iMiniBombCounter": "integer",
"m_iAmmoShells": "integer",
"m_iAmmoRockets": "integer",
"m_bPlayerControlled": "integer",
"m_nShieldLevel": "integer",
"m_hEnemy": "integer",
"m_hAutoAimTarget": "integer",
"m_iKills": "integer",
"m_iAssists": "integer",
"m_flRechargeTime": "float",
"m_flCurrentRechargeDuration": "float",
"m_iTimesUsed": "integer",
"m_flYawToExit": "float",
"m_bMatchBuilding": "integer",
"m_vOrigin": "vector",
"m_vDirection": "vector",
"m_bDisplayPerf": "integer",
"m_bMeasurePerf": "integer",
"m_iEffectIndex": "integer",
"m_bWeatherEffect": "integer",
"m_iCollisionCount": "integer",
"m_hHomingTarget": "integer",
"m_hCarrier": "integer",
"m_hPrevCarrier": "integer",
"m_bLowered": "integer",
"m_bResetParity": "integer",
"m_iReloadMode": "integer",
"m_bReloadedThroughAnimEvent": "integer",
"m_bDisguiseWeapon": "integer",
"m_flLastCritCheckTime": "float",
"m_flReloadPriorNextFire": "float",
"m_flLastFireTime": "float",
"m_flEffectBarRegenTime": "float",
"m_flObservedCritChance": "float",
"m_flEnergy": "float",
"m_hExtraWearable": "integer",
"m_hExtraWearableViewModel": "integer",
"m_bBeingRepurposedForTaunt": "integer",
"m_nKillComboClass": "integer",
"m_nKillComboCount": "integer",
"m_flInspectAnimEndTime": "float",
"m_nInspectStage": "integer",
"m_iConsecutiveShots": "integer",
"m_eThrowState": "integer",
"m_fChargeBeginTime": "float",
"m_iPhysicsMode": "integer",
"m_fMass": "float",
"m_bAwake": "integer",
"m_collisionMins": "vector",
"m_collisionMaxs": "vector",
"m_nPlasmaModelIndex": "integer",
"m_nPlasmaModelIndex2": "integer",
"m_nGlowModelIndex": "integer",
"m_FOV": "float",
"m_Resolution": "float",
"m_bFogEnable": "integer",
"m_FogColor": "integer",
"m_flFogStart": "float",
"m_flFogEnd": "float",
"m_flFogMaxDensity": "float",
"m_bUseScreenAspectRatio": "integer",
"m_iszCommentaryFile": "string",
"m_iszCommentaryFileNoHDR": "string",
"m_iszSpeakers": "string",
"m_iNodeNumber": "integer",
"m_iNodeNumberMax": "integer",
"m_hViewPosition": "integer",
"m_szText": "string",
"m_colTextColor": "integer",
"m_flTextSize": "float",
"m_flTextSpacingX": "float",
"m_flTextSpacingY": "float",
"m_nOrientation": "integer",
"m_nFont": "integer",
"m_bRainbow": "integer",
"m_bPoseValueParity": "integer",
"m_fPoseValue": "float",
"m_fInterpolationTime": "float",
"m_bInterpolationWrap": "integer",
"m_fCycleFrequency": "float",
"m_nFModType": "integer",
"m_fFModTimeOffset": "float",
"m_fFModRate": "float",
"m_fFModAmplitude": "float",
"m_nPrecipType": "integer",
"m_hPlayer": "integer",
"m_nRPM": "integer",
"m_flThrottle": "float",
"m_nBoostTimeLeft": "integer",
"m_nHasBoost": "integer",
"m_nScannerDisabledWeapons": "integer",
"m_nScannerDisabledVehicle": "integer",
"m_bEnterAnimOn": "integer",
"m_bExitAnimOn": "integer",
"m_bUnableToFire": "integer",
"m_vecEyeExitEndpoint": "vector",
"m_bHasGun": "integer",
"m_vecGunCrosshair": "vector",
"m_iCurrentMaxRagdollCount": "integer",
"m_ragAngles": "array",
"m_ragPos": "array",
"m_hUnragdoll": "integer",
"m_flBlendWeight": "float",
"m_nOverlaySequence": "integer",
"m_boneIndexAttached": "integer",
"m_ragdollAttachedObjectIndex": "integer",
"m_attachmentPointBoneSpace": "vector",
"m_attachmentPointRagdollSpace": "vector",
"m_hStartPoint": "integer",
"m_hEndPoint": "integer",
"m_iStartAttachment": "integer",
"m_iEndAttachment": "integer",
"m_Slack": "integer",
"m_RopeLength": "integer",
"m_fLockedPoints": "integer",
"m_RopeFlags": "integer",
"m_nSegments": "integer",
"m_bConstrainBetweenEndpoints": "integer",
"m_iRopeMaterialModelIndex": "integer",
"m_Subdiv": "integer",
"m_TextureScale": "float",
"m_Width": "float",
"m_flScrollSpeed": "float",
"m_nSceneStringIndex": "integer",
"m_bIsPlayingBack": "integer",
"m_bPaused": "integer",
"m_bMultiplayer": "integer",
"m_flForceClientTime": "float",
"m_shadowDirection": "vector",
"m_shadowColor": "integer",
"m_flShadowMaxDist": "float",
"m_bDisableShadows": "integer",
"m_szDisplayText": "string",
"m_szSlideshowDirectory": "string",
"m_fMinSlideTime": "float",
"m_fMaxSlideTime": "float",
"m_iCycleType": "integer",
"m_bNoListRepeats": "integer",
"m_SpreadSpeed": "float",
"m_Speed": "float",
"m_StartSize": "float",
"m_EndSize": "float",
"m_Rate": "float",
"m_JetLength": "float",
"m_flBaseSpread": "float",
"m_flRollSpeed": "float",
"m_DirLight.m_vPos": "vector",
"m_DirLight.m_vColor": "vector",
"m_DirLight.m_flIntensity": "float",
"m_AmbientLight.m_vPos": "vector",
"m_AmbientLight.m_vColor": "vector",
"m_AmbientLight.m_flIntensity": "float",
"m_vWind": "vector",
"m_flTwist": "float",
"m_iMaterialModel": "integer",
"m_flLightScale": "float",
"m_hAttachedToEntity": "integer",
"m_flSpriteScale": "float",
"m_flSpriteFramerate": "float",
"m_flBrightnessTime": "float",
"m_nBrightness": "integer",
"m_bWorldSpaceScale": "integer",
"m_flLifeTime": "float",
"m_flStartWidth": "float",
"m_flEndWidth": "float",
"m_flStartWidthVariance": "float",
"m_flTextureRes": "float",
"m_flMinFadeLength": "float",
"m_vecSkyboxOrigin": "vector",
"m_flSkyboxScale": "float",
"m_bFaceLeft": "integer",
"m_clrOverlay": "integer",
"m_bOn": "integer",
"m_nSize": "integer",
"m_nOverlaySize": "integer",
"m_nMaterial": "integer",
"m_nOverlayMaterial": "integer",
"m_iScore": "integer",
"m_iRoundsWon": "integer",
"m_szTeamname": "string",
"m_iRoundState": "integer",
"m_bInWaitingForPlayers": "integer",
"m_iWinningTeam": "integer",
"m_bInOvertime": "integer",
"m_bInSetup": "integer",
"m_bSwitchedTeamsThisRound": "integer",
"m_bAwaitingReadyRestart": "integer",
"m_flRestartRoundTime": "float",
"m_flMapResetTime": "float",
"m_nRoundsPlayed": "integer",
"m_bStopWatch": "integer",
"m_bMultipleTrains": "integer",
"m_bCheatsEnabledDuringLevel": "integer",
"m_flCountdownTime": "float",
"m_flStateTransitionTime": "float",
"m_bTimerPaused": "integer",
"m_flTimeRemaining": "float",
"m_flTimerEndTime": "float",
"m_nTimerMaxLength": "integer",
"m_bIsDisabled": "integer",
"m_bShowInHUD": "integer",
"m_nTimerLength": "integer",
"m_nTimerInitialLength": "integer",
"m_bAutoCountdown": "integer",
"m_nSetupTimeLength": "integer",
"m_nState": "integer",
"m_bStartPaused": "integer",
"m_bShowTimeRemaining": "integer",
"m_bStopWatchTimer": "integer",
"m_bInCaptureWatchState": "integer",
"m_flTotalTime": "float",
"m_flTotalProgress": "float",
"m_iTrainSpeedLevel": "integer",
"m_flRecedeTime": "float",
"m_nNumCappers": "integer",
"m_hGlowEnt": "integer",
"m_vecPos": "vector",
"m_vecDir": "vector",
"m_nStartFrame": "integer",
"m_nFrameRate": "integer",
"m_fLife": "float",
"m_nFadeLength": "integer",
"m_nStartEntity": "integer",
"m_nEndEntity": "integer",
"m_vecStartPoint": "vector",
"m_vecEndPoint": "vector",
"m_iEntIndex": "integer",
"m_vecCenter": "vector",
"m_flStartRadius": "float",
"m_flEndRadius": "float",
"m_nPoints": "integer",
"m_vecPoints": "array",
"m_vecDirection": "vector",
"m_nSprayModel": "integer",
"m_nDropModel": "integer",
"m_vecOrigin[0]": "float",
"m_vecOrigin[1]": "float",
"m_vecOrigin[2]": "float",
"m_nAmount": "integer",
"m_vecSize": "vector",
"m_nRandomization": "integer",
"m_nCount": "integer",
"m_fTime": "float",
"m_nEntity": "integer",
"m_nIndex": "integer",
"m_fHeight": "float",
"m_flWaterZ": "float",
"m_nLifeTime": "integer",
"m_vecStart": "vector",
"m_nHitbox": "integer",
"m_flSize": "float",
"m_flSpeed": "float",
"m_fRadius": "float",
"m_fDecay": "float",
"m_vOrigin[0]": "float",
"m_vOrigin[1]": "float",
"m_vOrigin[2]": "float",
"m_vStart[0]": "float",
"m_vStart[1]": "float",
"m_vStart[2]": "float",
"m_vAngles": "vector",
"m_flMagnitude": "float",
"m_nAttachmentIndex": "integer",
"m_nSurfaceProp": "integer",
"m_iEffectName": "integer",
"m_nDamageType": "integer",
"m_nHitBox": "integer",
"m_nColor": "integer",
"m_flRadius": "float",
"m_bCustomColors": "integer",
"m_CustomColors.m_vecColor1": "vector",
"m_CustomColors.m_vecColor2": "vector",
"m_bControlPoint1": "integer",
"m_ControlPoint1.m_eParticleAttachment": "integer",
"m_ControlPoint1.m_vecOffset[0]": "float",
"m_ControlPoint1.m_vecOffset[1]": "float",
"m_ControlPoint1.m_vecOffset[2]": "float",
"m_bExplosive": "integer",
"m_fScale": "float",
"m_vecNormal": "vector",
"m_chMaterialType": "integer",
"m_nRadius": "integer",
"m_vecAngles[0]": "float",
"m_vecAngles[1]": "float",
"m_iWeaponID": "integer",
"m_iMode": "integer",
"m_iSeed": "integer",
"m_iPlayer": "integer",
"m_flSpread": "float",
"m_bCritical": "integer",
"m_nCurrent": "integer",
"m_iType": "integer",
"m_nPlayer": "integer",
"m_nReversed": "integer",
"m_vecAngles": "vector",
"m_nEffects": "integer",
"m_iEvent": "integer",
"m_nData": "integer",
"m_flDistance": "float",
"m_vecForcePos": "vector",
"m_flHeight": "float",
"m_flShardSize": "float",
"m_uchFrontColor[0]": "integer",
"m_uchFrontColor[1]": "integer",
"m_uchFrontColor[2]": "integer",
"m_uchBackColor[0]": "integer",
"m_uchBackColor[1]": "integer",
"m_uchBackColor[2]": "integer",
"m_vecEnd": "vector",
"m_SoundName": "string",
"m_iszSpriteName": "string",
"m_nTrailLength": "integer",
"m_fNoise": "float",
"m_WithProxy": "integer",
"m_nDefID": "integer",
"m_nSound": "integer",
"m_iCustomParticleIndex": "integer",
"m_vecStart[0]": "float",
"m_vecStart[1]": "float",
"m_vecStart[2]": "float",
"m_iParticleSystemIndex": "integer",
"m_iAttachType": "integer",
"m_iAttachmentPointIndex": "integer",
"m_bResetParticles": "integer",
"m_vecInitialVelocity": "vector",
"m_vInitialVelocity": "vector",
"m_iDeflected": "integer",
"m_hDeflectOwner": "integer",
"m_bTouched": "integer",
"m_hLauncher": "integer",
"m_bDefensiveBomb": "integer",
"m_lastHealthPercentage": "float",
"m_bHasActiveTeleporter": "integer",
"m_bBroken": "integer",
"m_flDetonateTime": "float",
"m_iCurrentTube": "integer",
"m_iGoalTube": "integer",
"m_flMinicritCharge": "float",
"m_iPipebombCount": "integer",
"m_flChargeBeginTime": "float",
"m_bArrowAlight": "integer",
"m_bNoFire": "integer",
"m_flRegenerateDuration": "float",
"m_flLastUsedTimestamp": "float",
"m_bUseNewProjectileCode": "integer",
"m_flChargeLevel": "float",
"m_nRandomSeed": "integer",
"m_unNextPointIndex": "integer",
"m_hAttacker": "integer",
"m_flSpreadDegree": "float",
"m_flRedirectedFlameSizeMult": "float",
"m_flFlameStartSizeMult": "float",
"m_flFlameEndSizeMult": "float",
"m_flFlameIgnorePlayerVelocity": "float",
"m_flFlameReflectionAdditionalLifeTime": "float",
"m_flFlameReflectionDamageReduction": "float",
"m_iMaxFlameReflectionCount": "integer",
"m_nShouldReflect": "integer",
"m_flFlameSpeed": "float",
"m_flFlameLifeTime": "float",
"m_flRandomLifeTimeOffset": "float",
"m_flFlameGravity": "float",
"m_flFlameDrag": "float",
"m_flFlameUp": "float",
"m_bIsFiring": "integer",
"m_iWeaponState": "integer",
"m_bCritFire": "integer",
"m_bHitTarget": "integer",
"m_iActiveFlames": "integer",
"m_iDamagingFlames": "integer",
"m_hFlameManager": "integer",
"m_bHasHalloweenSpell": "integer",
"m_fLastExtinguishTime": "float",
"m_nGameType": "integer",
"m_nStopWatchState": "integer",
"m_pszTeamGoalStringRed": "string",
"m_pszTeamGoalStringBlue": "string",
"m_flCapturePointEnableTime": "float",
"m_nHudType": "integer",
"m_bIsInTraining": "integer",
"m_bAllowTrainingAchievements": "integer",
"m_bIsWaitingForTrainingContinue": "integer",
"m_bIsTrainingHUDVisible": "integer",
"m_bIsInItemTestingMode": "integer",
"m_hBonusLogic": "integer",
"m_bPlayingKoth": "integer",
"m_bPlayingMedieval": "integer",
"m_bPlayingHybrid_CTF_CP": "integer",
"m_bPlayingSpecialDeliveryMode": "integer",
"m_bPlayingRobotDestructionMode": "integer",
"m_hRedKothTimer": "integer",
"m_hBlueKothTimer": "integer",
"m_nMapHolidayType": "integer",
"m_itHandle": "integer",
"m_bPlayingMannVsMachine": "integer",
"m_hBirthdayPlayer": "integer",
"m_nBossHealth": "integer",
"m_nMaxBossHealth": "integer",
"m_fBossNormalizedTravelDistance": "integer",
"m_bMannVsMachineAlarmStatus": "integer",
"m_bHaveMinPlayersToEnableReady": "integer",
"m_bBountyModeEnabled": "integer",
"m_nHalloweenEffect": "integer",
"m_fHalloweenEffectStartTime": "float",
"m_fHalloweenEffectDuration": "float",
"m_halloweenScenario": "integer",
"m_bHelltowerPlayersInHell": "integer",
"m_bIsUsingSpells": "integer",
"m_bCompetitiveMode": "integer",
"m_bPowerupMode": "integer",
"m_nMatchGroupType": "integer",
"m_bMatchEnded": "integer",
"m_pszCustomUpgradesFile": "string",
"m_bTruceActive": "integer",
"m_bShowMatchSummary": "integer",
"m_bTeamsSwitched": "integer",
"m_bMapHasMatchSummaryStage": "integer",
"m_bPlayersAreOnMatchSummaryStage": "integer",
"m_bStopWatchWinner": "integer",
"m_eRematchState": "integer",
"m_nForceUpgrades": "integer",
"m_nForceEscortPushLogic": "integer",
"m_bRopesHolidayLightsAllowed": "integer",
"m_glowColor": "integer",
"m_hProjectile": "integer",
"m_nMaxScoreForMiniGame": "integer",
"m_pszHudResFile": "string",
"m_eScoringType": "integer",
"m_bIsBloody": "integer",
"m_bReadyToBackstab": "integer",
"m_bKnifeExists": "integer",
"m_flKnifeRegenerateDuration": "float",
"m_flKnifeMeltTimestamp": "float",
"m_hActiveMinigame": "integer",
"m_bCritShot": "integer",
"m_nMannVsMachineMaxWaveCount": "integer",
"m_nMannVsMachineWaveCount": "integer",
"m_nMannVsMachineWaveEnemyCount": "integer",
"m_nMvMWorldMoney": "integer",
"m_flMannVsMachineNextWaveTime": "float",
"m_bMannVsMachineBetweenWaves": "integer",
"m_nFlagCarrierUpgradeLevel": "integer",
"m_flMvMBaseBombUpgradeTime": "float",
"m_flMvMNextBombUpgradeTime": "float",
"m_iszMvMPopfileName": "string",
"m_iChallengeIndex": "integer",
"m_nMvMEventPopfileType": "integer",
"m_iszMannVsMachineWaveClassNames": "array",
"m_iszMannVsMachineWaveClassNames2": "array",
"m_iChargeEffect": "integer",
"m_hBall": "integer",
"m_trackPoints": "array",
"m_iNumSections": "integer",
"m_iCurrentSection": "integer",
"m_flMaxPassRange": "float",
"m_iBallPower": "integer",
"m_flPackSpeed": "float",
"m_flexWeight": "integer",
"m_bSaveMeParity": "integer",
"m_bIsMiniBoss": "integer",
"m_bIsABot": "integer",
"m_nBotSkill": "integer",
"m_hRagdoll": "integer",
"m_iClass": "integer",
"m_iszClassIcon": "string",
"m_iszCustomModel": "string",
"m_vecCustomModelOffset": "vector",
"m_angCustomModelRotation": "vector",
"m_bCustomModelRotates": "integer",
"m_bCustomModelRotationSet": "integer",
"m_bCustomModelVisibleToSelf": "integer",
"m_bUseClassAnimations": "integer",
"m_iClassModelParity": "integer",
"m_nPlayerCond": "integer",
"m_bJumping": "integer",
"m_nNumHealers": "integer",
"m_iCritMult": "integer",
"m_iAirDash": "integer",
"m_nAirDucked": "integer",
"m_flDuckTimer": "float",
"m_nPlayerState": "integer",
"m_iDesiredPlayerClass": "integer",
"m_flMovementStunTime": "float",
"m_iMovementStunAmount": "integer",
"m_iMovementStunParity": "integer",
"m_hStunner": "integer",
"m_iStunFlags": "integer",
"m_nArenaNumChanges": "integer",
"m_bArenaFirstBloodBoost": "integer",
"m_iWeaponKnockbackID": "integer",
"m_bLoadoutUnavailable": "integer",
"m_iItemFindBonus": "integer",
"m_bShieldEquipped": "integer",
"m_bParachuteEquipped": "integer",
"m_iNextMeleeCrit": "integer",
"m_iDecapitations": "integer",
"m_iRevengeCrits": "integer",
"m_iDisguiseBody": "integer",
"m_hCarriedObject": "integer",
"m_bCarryingObject": "integer",
"m_flNextNoiseMakerTime": "float",
"m_iSpawnRoomTouchCount": "integer",
"m_iKillCountSinceLastDeploy": "integer",
"m_flFirstPrimaryAttack": "float",
"m_flEnergyDrinkMeter": "float",
"m_flHypeMeter": "float",
"m_flChargeMeter": "float",
"m_flInvisChangeCompleteTime": "float",
"m_nDisguiseTeam": "integer",
"m_nDisguiseClass": "integer",
"m_nDisguiseSkinOverride": "integer",
"m_nMaskClass": "integer",
"m_hDisguiseTarget": "integer",
"m_iDisguiseHealth": "integer",
"m_bFeignDeathReady": "integer",
"m_hDisguiseWeapon": "integer",
"m_nTeamTeleporterUsed": "integer",
"m_flCloakMeter": "float",
"m_flSpyTranqBuffDuration": "float",
"m_nDesiredDisguiseTeam": "integer",
"m_nDesiredDisguiseClass": "integer",
"m_bLastDisguisedAsOwnTeam": "integer",
"m_flStealthNoAttackExpire": "float",
"m_flStealthNextChangeTime": "float",
"m_flRageMeter": "float",
"m_bRageDraining": "integer",
"m_flNextRageEarnTime": "float",
"m_bInUpgradeZone": "integer",
"m_iCaptures": "integer",
"m_iDefenses": "integer",
"m_iDeaths": "integer",
"m_iSuicides": "integer",
"m_iDominations": "integer",
"m_iRevenge": "integer",
"m_iBuildingsBuilt": "integer",
"m_iBuildingsDestroyed": "integer",
"m_iHeadshots": "integer",
"m_iBackstabs": "integer",
"m_iHealPoints": "integer",
"m_iInvulns": "integer",
"m_iTeleports": "integer",
"m_iDamageDone": "integer",
"m_iCrits": "integer",
"m_iResupplyPoints": "integer",
"m_iKillAssists": "integer",
"m_iBonusPoints": "integer",
"m_iPoints": "integer",
"m_iTauntIndex": "integer",
"m_iTauntConcept": "integer",
"m_nPlayerCondEx": "integer",
"m_iStunIndex": "integer",
"m_nHalloweenBombHeadStage": "integer",
"m_nPlayerCondEx2": "integer",
"m_nPlayerCondEx3": "integer",
"m_unTauntSourceItemID_Low": "integer",
"m_unTauntSourceItemID_High": "integer",
"m_flRuneCharge": "float",
"m_bHasPasstimeBall": "integer",
"m_bIsTargetedForPasstimePass": "integer",
"m_hPasstimePassTarget": "integer",
"m_askForBallTime": "float",
"m_bKingRuneBuffActive": "integer",
"m_pProvider": "integer",
"m_nPlayerCondEx4": "integer",
"m_flHolsterAnimTime": "float",
"m_hSwitchTo": "integer",
"m_hItem": "integer",
"m_angEyeAngles[0]": "float",
"m_angEyeAngles[1]": "float",
"m_bIsCoaching": "integer",
"m_hCoach": "integer",
"m_hStudent": "integer",
"m_nCurrency": "integer",
"m_nExperienceLevel": "integer",
"m_nExperienceLevelProgress": "integer",
"m_bMatchSafeToLeave": "integer",
"m_bAllowMoveDuringTaunt": "integer",
"m_bIsReadyToHighFive": "integer",
"m_hHighFivePartner": "integer",
"m_nForceTauntCam": "integer",
"m_flTauntYaw": "float",
"m_nActiveTauntSlot": "integer",
"m_iTauntItemDefIndex": "integer",
"m_flCurrentTauntMoveSpeed": "float",
"m_flVehicleReverseTime": "float",
"m_flMvMLastDamageTime": "float",
"m_bInPowerPlay": "integer",
"m_iSpawnCounter": "integer",
"m_bArenaSpectator": "integer",
"m_flHeadScale": "float",
"m_flTorsoScale": "float",
"m_flHandScale": "float",
"m_bUseBossHealthBar": "integer",
"m_bUsingVRHeadset": "integer",
"m_bForcedSkin": "integer",
"m_nForcedSkin": "integer",
"m_nActiveWpnClip": "integer",
"m_flKartNextAvailableBoost": "float",
"m_iKartHealth": "integer",
"m_iKartState": "integer",
"m_hGrapplingHookTarget": "integer",
"m_hSecondaryLastWeapon": "integer",
"m_bUsingActionSlot": "integer",
"m_flInspectTime": "float",
"m_flHelpmeButtonPressTime": "float",
"m_iCampaignMedals": "integer",
"m_iPlayerSkinOverride": "integer",
"m_bViewingCYOAPDA": "integer",
"m_bRegenerating": "integer",
"m_nMaxPoints": "integer",
"m_nBlueScore": "integer",
"m_nRedScore": "integer",
"m_nBlueTargetPoints": "integer",
"m_nRedTargetPoints": "integer",
"m_flBlueTeamRespawnScale": "float",
"m_flRedTeamRespawnScale": "float",
"m_flBlueFinaleEndTime": "float",
"m_flRedFinaleEndTime": "float",
"m_flFinaleLength": "float",
"m_szResFile": "string",
"m_flCountdownEndTime": "float",
"m_hRedTeamLeader": "integer",
"m_hBlueTeamLeader": "integer",
"m_iszCountdownImage": "string",
"m_bUsingCountdownImage": "integer",
"m_iPartyLeaderRedTeamIndex": "integer",
"m_iPartyLeaderBlueTeamIndex": "integer",
"m_iEventTeamStatus": "integer",
"m_bDisguiseWearable": "integer",
"m_hWeaponAssociatedWith": "integer",
"m_usNumCharges": "integer",
"m_iProjectileType": "integer",
"m_vecSpawnOrigin": "vector",
"m_bChargedShot": "integer",
"m_vColor1": "vector",
"m_vColor2": "vector",
"m_vecRagdollOrigin": "vector",
"m_vecRagdollVelocity": "vector",
"m_bGib": "integer",
"m_bBurning": "integer",
"m_bElectrocuted": "integer",
"m_bFeignDeath": "integer",
"m_bWasDisguised": "integer",
"m_bBecomeAsh": "integer",
"m_bOnGround": "integer",
"m_bCloaked": "integer",
"m_iDamageCustom": "integer",
"m_iTeam": "integer",
"m_bGoldRagdoll": "integer",
"m_bIceRagdoll": "integer",
"m_bCritOnHardHit": "integer",
"m_nRevives": "integer",
"m_hRobotArm": "integer",
"m_eType": "integer",
"m_pszHudIcon": "string",
"m_nGroupNumber": "integer",
"m_flRespawnStartTime": "float",
"m_flRespawnEndTime": "float",
"m_flLastAttackedTime": "float",
"m_flInitLaunchTime": "float",
"m_flLaunchTime": "float",
"m_flToggleEndTime": "float",
"m_bFirstHit": "integer",
"m_nNumKills": "integer",
"m_flChargedDamage": "float",
"m_bCharging": "integer",
"m_iSelectedSpellIndex": "integer",
"m_iSpellCharges": "integer",
"m_flTimeNextSpell": "float",
"m_bFiredAttack": "integer",
"m_iDetonated": "integer",
"m_nFlagCaptures": "integer",
"m_iRole": "integer",
"m_hLeader": "integer",
"m_iBuildState": "integer",
"m_hObjectBeingBuilt": "integer",
"m_flWheatleyTalkingUntil": "float",
"m_flRechargeScale": "float",
"m_unLevel": "integer",
"m_nPanelName": "integer",
"m_fScreenFlags": "integer",
"m_hPlayerOwner": "integer",
"m_iActiveIssueIndex": "integer",
"m_nVoteIdx": "integer",
"m_iOnlyTeamToVote": "integer",
"m_nPotentialVotes": "integer",
"m_bIsYesNoVote": "integer",
"m_flCheapWaterStartDistance": "float",
"m_flCheapWaterEndDistance": "float",
"m_flRenderAspectRatio": "float",
"m_flRenderFOV": "float",
"m_flRenderArmLength": "float",
"m_vecRenderPosition": "vector",
"m_angRenderAngles": "vector",
"m_hHealingTarget": "integer",
"m_bHealing": "integer",
"m_bAttacking": "integer",
"m_bChargeRelease": "integer",
"m_bHolstered": "integer",
"m_nChargeResistType": "integer",
"m_hLastHealingTarget": "integer",
"m_WorldMins": "vector",
"m_WorldMaxs": "vector",
"m_bStartDark": "integer",
"m_flMaxOccludeeArea": "float",
"m_flMinOccluderArea": "float",
"m_flMaxPropScreenSpaceWidth": "float",
"m_flMinPropScreenSpaceWidth": "float",
"m_iszDetailSpriteMaterial": "string",
"m_bColdWorld": "integer",
"m_ParticleLifetime": "float",
"m_StopEmitTime": "float",
"m_MinSpeed": "float",
"m_MaxSpeed": "float",
"m_MinDirectedSpeed": "float",
"m_MaxDirectedSpeed": "float",
"m_SpawnRadius": "float",
"m_Opacity": "float",
"m_flSpawnTime": "float",
"m_FadeStartTime": "float",
"m_FadeEndTime": "float",
"m_CurrentStage": "integer",
"m_StartColor": "vector",
"m_EndColor": "vector",
"m_bDamaged": "integer",
"m_flFlareScale": "float",
"m_flSpawnRate": "float",
"m_flParticleLifetime": "float",
"m_flSpawnRadius": "float",
"m_bDontRemove": "integer",
"m_vecEndColor": "vector",
}